version: '3'
services:
  dev:
    image: node:8-alpine
    volumes:
      - nodemodules:/root/appUI/node_modules
      - .:/root/appUI
    working_dir: /root/appUI
    command: yarn start
    ports:
      - 8000:8000
      - 8001:8001

volumes:
  nodemodules:
    external: true
