version: '2'
services:
  base:
    image: node:8-alpine
    volumes:
      - nodemodules:/root/appUI/node_modules
      - .:/root/appUI
    working_dir: /root/appUI

  install:
    extends:
      service: base
    command: yarn

  build:
    extends:
      service: base
    command: yarn build

volumes:
  nodemodules:
    external: true
