server:
  http:
    hostname: localhost
    port: 8000
    static:
      development:
        /public: server/public
        /assets: src/assets
        /build: build
        /dist: dist
      production:
        /public: server/public
        /assets: dist/assets
        /dist: dist

  # backend service gateway server
  gatewayServer:
    url: http://rap2.taobao.org:38080/app/mock/252252
    wsUrl: ws://ks-apigateway.demo-system.svc

client:
  title: Boilerplate

  # current support lanaguages
  supportLangs:
    - label: '简体中文'
      value: 'zh'
    - label: 'English'
      value: 'en'
  defaultLang: 'en'
  globalNavs:
    - name: welcome
      title: Welcome
      icon: iconsmile
    - name: navigation
      title: Navigation
      icon: iconsmile
      children:
        - { name: option1, title: Option 1, icon: iconsmile }
        - { name: option2, title: Option 2, icon: iconsmile }


